version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "UTC"
    versioning-strategy: "increase"
    groups:
      npm-production:
        dependency-type: "production"
      npm-development:
        dependency-type: "development"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
